### PR TITLE
SHVDN Version 3 Compatibility

### PR DESCRIPTION
**Pull request by Ro9ueAdmin**
- Added compatibility with ScriptHookVDotNET v3

- Bit more Reader Friendly

- Fully Works

### CODE REVIEW

**Comment by justalemon** [comment]
I'm going to merge this locally later because I plan to make some extra changes.

**Comment by Ro9ueAdmin** [comment]
Sounds good and ill of course leave it to you if you wanna publish the changes to the gta5-mods website cuz I cant even login to my account for some reason.

**Comment by Ro9ueAdmin** [comment]
BTW Here is a quick release i made for the SHVDN Version 3 in case you wanna add it to your releases:
https://github.com/Ro9ueAdmin/ControllerReload/releases/tag/2.0

**Comment by justalemon** [comment]
All of my builds are automatically done when they are new tags detected by AppVeyor.

**Pull request merged**
